name: Add Reactions
on:
  issue_comment:
jobs:
  add-reactions:
    permissions:
      issues: write  # for peter-evans/create-or-update-comment to create or update comment
      pull-requests: write  # for peter-evans/create-or-update-comment to create or update comment
    runs-on: ubuntu-latest
    steps:
    - name: Find First Issue Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.issue.number }}
        comment-author: ${{ github.event.issue.user.login }}
    - run: |
        echo ${{ steps.fc.outputs.comment-id }}
        echo ${{ steps.fc.outputs.comment-body }}
        echo ${{ steps.fc.outputs.comment-author }}
    - name: Add reactions
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        reactions: |
          heart
          hooray
          laugh
