name: lighthouse
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run:  |
        npm install
        npm run build
    - name: Run lighthouse
      run: |
        npm install -g @lhci/cli@0.13.x
        lhci autorun
