name: lighthouse
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use NodeJS 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run:  |
        npm install
        npm run build
    - name: Run lighthouse
      run: |
        npm install -g @lhci/cli@0.13.x
        lhci autorun
