name: proof-html
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  proof-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run:  |
          npm install
          npm run build
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./dist
          check_favicon: false
          enforce_https: false
          ignore_url: |
            http://webpack.js.org/guides/getting-started/
            https://webpack.js.org/guides/getting-started/
          ignore_url_re: |
            ^https://webpack.js.org/
